#!/usr/bin/env python3
"""
Star Trek Retro Remake - Compiled UI Package

Description:
    Compiled Python classes generated from Qt Designer .ui files.
    These files are auto-generated by pyside6-uic and should not be
    manually edited.

Author: Star Trek Retro Remake Development Team
Email: development@star-trek-retro-remake.org
GitHub: https://github.com/L3DigitalNet/Star-Trek-Retro-Remake
Date Created: 11-01-2025
Date Changed: 11-01-2025
License: MIT

Features:
    - Compiled UI classes for better performance
    - Type-safe UI element access
    - Compile-time UI validation

Requirements:
    - Linux environment
    - Python 3.14+ for latest language features
    - PySide6 for Qt UI framework

Note:
    These files are automatically generated from .ui files in the designer/
    directory using the scripts/compile_ui.py script. Do not edit manually.
"""

from typing import Final

__version__: Final[str] = "0.0.27"
